cmake_minimum_required(VERSION 3.16)

ADD_SUBDIRECTORY(${CMAKE_CURRENT_SOURCE_DIR}/../lite/c ${CMAKE_CURRENT_BINARY_DIR}/lite)

#set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/../../../lib/x64)
#set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/../../../lib/x64)
#set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/../../../lib/x64)

PROJECT(tfliteextern)
INCLUDE_DIRECTORIES("${CMAKE_CURRENT_SOURCE_DIR}" "${CMAKE_CURRENT_SOURCE_DIR}/../imgproc")
#INCLUDE_DIRECTORIES("${CMAKE_CURRENT_SOURCE_DIR}/../../")
#INCLUDE_DIRECTORIES("${CMAKE_CACHEFILE_DIR}")


add_library(tfliteextern SHARED tfliteextern.h tfliteextern.cc ${CMAKE_CURRENT_SOURCE_DIR}/../imgproc/imgproc.h ${CMAKE_CURRENT_SOURCE_DIR}/../imgproc/imgproc.cc)

target_link_libraries(tfliteextern
  tensorflow-lite
)
ADD_DEPENDENCIES(tfliteextern tensorflow-lite)

IF(MSVC AND CMAKE_CL_64)
  SET(TARGET_ARCH_64 TRUE)
ELSE()
  IF((CMAKE_SIZEOF_VOID_P EQUAL 8) AND NOT(APPLE AND CMAKE_OSX_ARCHITECTURES MATCHES "i386"))
    SET(TARGET_ARCH_64 TRUE)
  ENDIF() 
ENDIF()

IF(TARGET_ARCH_64)
  SET(BINARY_OUTPUT_SUBFOLDER "x64") 
ELSE()
  SET(BINARY_OUTPUT_SUBFOLDER "x86")
ENDIF()

IF(WIN32 AND MSVC AND (NOT NETFX_CORE))
  # Add install rules for required system runtimes such as MSVCRxx.dll
  SET (CMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP ON)
  INCLUDE(InstallRequiredSystemLibraries)
  LIST(APPEND TFLITEEXTERN_DEPENDENCY_DLLS ${CMAKE_INSTALL_SYSTEM_RUNTIME_LIBS})   
ENDIF()

IF (MSVC)
  SET(TFLITEEXTERN_OUTPUT_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/../../../lib/${BINARY_OUTPUT_SUBFOLDER})
  set_target_properties( tfliteextern PROPERTIES RUNTIME_OUTPUT_DIRECTORY ${TFLITEEXTERN_OUTPUT_DIRECTORY} )
  set_target_properties( tfliteextern PROPERTIES RUNTIME_OUTPUT_DIRECTORY_DEBUG ${TFLITEEXTERN_OUTPUT_DIRECTORY} )
  set_target_properties( tfliteextern PROPERTIES RUNTIME_OUTPUT_DIRECTORY_RELEASE ${TFLITEEXTERN_OUTPUT_DIRECTORY} )
  
  IF(DEFINED TFLITEEXTERN_DEPENDENCY_DLLS)
  FOREACH(TFLITEEXTERN_DEPENDENCY_DLL ${TFLITEEXTERN_DEPENDENCY_DLLS})
    LIST(APPEND TFLITEEXTERN_DEPENDENCY_DLL_DEPLOY_COMMAND COMMAND ${CMAKE_COMMAND} -E copy "${TFLITEEXTERN_DEPENDENCY_DLL}" "${TFLITEEXTERN_OUTPUT_DIRECTORY}")
	#MESSAGE(STATUS "**************${CMAKE_COMMAND} -E copy ${TFLITEEXTERN_DEPENDENCY_DLL} ${TFLITEEXTERN_OUTPUT_DIRECTORY}")
    #GET_FILENAME_COMPONENT(TFLITEEXTERN_DEPENDENCT_DLL_NAME ${CVEXTERN_DEPENDENCY_DLL} NAME_WE)
    #LIST(APPEND TFLITEEXTERN_DEPENDENCY_DLL_NAMES ${TFLITEEXTERN_DEPENDENCT_DLL_NAME})
  ENDFOREACH()
  
  #Promote this to parent scope such that cpack will know what dlls to be included in the package
  #MESSAGE("**************CVEXTERN_DEPENDENCY_DLL_NAMES: ${CVEXTERN_DEPENDENCY_DLL_NAMES}")
  #SET(TFLITEEXTERN_DEPENDENCY_DLL_NAMES ${TFLITEEXTERN_DEPENDENCY_DLL_NAMES} PARENT_SCOPE)
  
  ADD_CUSTOM_COMMAND(
    TARGET tfliteextern
    POST_BUILD
    ${TFLITEEXTERN_DEPENDENCY_DLL_DEPLOY_COMMAND}
    COMMENT "Copying ${TFLITEEXTERN_DEPENDENCY_DLLS} to ${CMAKE_RUNTIME_OUTPUT_DIRECTORY}")
ENDIF()
  
ENDIF()
