
ADD_SUBDIRECTORY(${CMAKE_CURRENT_SOURCE_DIR}/../lite/c ${CMAKE_CURRENT_BINARY_DIR}/lite)

#set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/../../../lib/x64)
#set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/../../../lib/x64)
#set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/../../../lib/x64)

PROJECT(tfliteextern)
INCLUDE_DIRECTORIES("${CMAKE_CURRENT_SOURCE_DIR}")
#INCLUDE_DIRECTORIES("${CMAKE_CURRENT_SOURCE_DIR}/../../")
#INCLUDE_DIRECTORIES("${CMAKE_CACHEFILE_DIR}")


add_library(tfliteextern SHARED tfliteextern.cc tfliteextern.h  )
target_link_libraries(tfliteextern
  tensorflow-lite
)
ADD_DEPENDENCIES(tfliteextern tensorflow-lite)

IF (MSVC)
  SET(TFLITEEXTERN_OUTPUT_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/../../../lib/x64)
  set_target_properties( tfliteextern PROPERTIES RUNTIME_OUTPUT_DIRECTORY ${TFLITEEXTERN_OUTPUT_DIRECTORY} )
  set_target_properties( tfliteextern PROPERTIES RUNTIME_OUTPUT_DIRECTORY_DEBUG ${TFLITEEXTERN_OUTPUT_DIRECTORY} )
  set_target_properties( tfliteextern PROPERTIES RUNTIME_OUTPUT_DIRECTORY_RELEASE ${TFLITEEXTERN_OUTPUT_DIRECTORY} )
ENDIF()
