
ADD_SUBDIRECTORY(${CMAKE_CURRENT_SOURCE_DIR}/../lite/c ${CMAKE_CURRENT_BINARY_DIR}/lite)

#set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/../../../lib/x64)
#set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/../../../lib/x64)
#set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/../../../lib/x64)

PROJECT(tfliteextern)
INCLUDE_DIRECTORIES("${CMAKE_CURRENT_SOURCE_DIR}" "${CMAKE_CURRENT_SOURCE_DIR}/../imgproc")
#INCLUDE_DIRECTORIES("${CMAKE_CURRENT_SOURCE_DIR}/../../")
#INCLUDE_DIRECTORIES("${CMAKE_CACHEFILE_DIR}")


add_library(tfliteextern SHARED tfliteextern.h tfliteextern.cc ${CMAKE_CURRENT_SOURCE_DIR}/../imgproc/imgproc.h ${CMAKE_CURRENT_SOURCE_DIR}/../imgproc/imgproc.cc)

target_link_libraries(tfliteextern
  tensorflow-lite
)
ADD_DEPENDENCIES(tfliteextern tensorflow-lite)

IF(MSVC AND CMAKE_CL_64)
  SET(TARGET_ARCH_64 TRUE)
ELSE()
  IF((CMAKE_SIZEOF_VOID_P EQUAL 8) AND NOT(APPLE AND CMAKE_OSX_ARCHITECTURES MATCHES "i386"))
    SET(TARGET_ARCH_64 TRUE)
  ENDIF() 
ENDIF()

IF(TARGET_ARCH_64)
  SET(BINARY_OUTPUT_SUBFOLDER "x64") 
ELSE()
  SET(BINARY_OUTPUT_SUBFOLDER "x86")
ENDIF()

IF (MSVC)
  SET(TFLITEEXTERN_OUTPUT_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/../../../lib/${BINARY_OUTPUT_SUBFOLDER})
  set_target_properties( tfliteextern PROPERTIES RUNTIME_OUTPUT_DIRECTORY ${TFLITEEXTERN_OUTPUT_DIRECTORY} )
  set_target_properties( tfliteextern PROPERTIES RUNTIME_OUTPUT_DIRECTORY_DEBUG ${TFLITEEXTERN_OUTPUT_DIRECTORY} )
  set_target_properties( tfliteextern PROPERTIES RUNTIME_OUTPUT_DIRECTORY_RELEASE ${TFLITEEXTERN_OUTPUT_DIRECTORY} )
ENDIF()
